#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 4

enum {
  sym_identifier = 1,
  sym_chunks = 2,
  anon_sym_LPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_RPAREN = 5,
  anon_sym_STAR = 6,
  anon_sym_SLASH = 7,
  anon_sym_PLUS = 8,
  anon_sym_DASH = 9,
  anon_sym_AMP = 10,
  anon_sym_PIPE = 11,
  anon_sym_LT = 12,
  anon_sym_GT = 13,
  anon_sym_LT_EQ = 14,
  anon_sym_GT_EQ = 15,
  anon_sym_EQ = 16,
  anon_sym_LT_GT = 17,
  anon_sym_SEMI = 18,
  anon_sym_if = 19,
  anon_sym_then = 20,
  anon_sym_else = 21,
  anon_sym_while = 22,
  anon_sym_do = 23,
  sym_number_literal = 24,
  sym_string_literal = 25,
  sym_nil = 26,
  sym_comment = 27,
  sym_program = 28,
  sym__expr = 29,
  sym_func_call = 30,
  sym_binop = 31,
  sym_unop = 32,
  sym__parenthesis_exp = 33,
  sym_if_expr = 34,
  sym_while_expr = 35,
  aux_sym_func_call_repeat1 = 36,
  aux_sym__parenthesis_exp_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_chunks] = "chunks",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ] = "=",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_SEMI] = ";",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_do] = "do",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [sym_nil] = "nil",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym__expr] = "_expr",
  [sym_func_call] = "func_call",
  [sym_binop] = "binop",
  [sym_unop] = "unop",
  [sym__parenthesis_exp] = "_parenthesis_exp",
  [sym_if_expr] = "if_expr",
  [sym_while_expr] = "while_expr",
  [aux_sym_func_call_repeat1] = "func_call_repeat1",
  [aux_sym__parenthesis_exp_repeat1] = "_parenthesis_exp_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_chunks] = sym_chunks,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_do] = anon_sym_do,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_nil] = sym_nil,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym__expr] = sym__expr,
  [sym_func_call] = sym_func_call,
  [sym_binop] = sym_binop,
  [sym_unop] = sym_unop,
  [sym__parenthesis_exp] = sym__parenthesis_exp,
  [sym_if_expr] = sym_if_expr,
  [sym_while_expr] = sym_while_expr,
  [aux_sym_func_call_repeat1] = aux_sym_func_call_repeat1,
  [aux_sym__parenthesis_exp_repeat1] = aux_sym__parenthesis_exp_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_chunks] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_func_call] = {
    .visible = true,
    .named = true,
  },
  [sym_binop] = {
    .visible = true,
    .named = true,
  },
  [sym_unop] = {
    .visible = true,
    .named = true,
  },
  [sym__parenthesis_exp] = {
    .visible = false,
    .named = true,
  },
  [sym_if_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_while_expr] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_func_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parenthesis_exp_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_condition = 2,
  field_else = 3,
  field_func_name = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_condition] = "condition",
  [field_else] = "else",
  [field_func_name] = "func_name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_func_name, 0},
  [1] =
    {field_body, 3},
    {field_condition, 1},
  [3] =
    {field_body, 3},
    {field_condition, 1},
    {field_else, 4},
    {field_else, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 16,
  [20] = 20,
  [21] = 21,
  [22] = 21,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 28,
  [29] = 29,
  [30] = 28,
  [31] = 25,
  [32] = 32,
  [33] = 33,
  [34] = 29,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 24,
  [39] = 33,
  [40] = 23,
  [41] = 41,
  [42] = 20,
  [43] = 41,
  [44] = 37,
  [45] = 35,
  [46] = 10,
  [47] = 15,
  [48] = 3,
  [49] = 13,
  [50] = 4,
  [51] = 51,
  [52] = 12,
  [53] = 5,
  [54] = 6,
  [55] = 11,
  [56] = 14,
  [57] = 9,
  [58] = 7,
  [59] = 59,
  [60] = 8,
  [61] = 2,
  [62] = 62,
  [63] = 62,
  [64] = 64,
  [65] = 64,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 69,
  [71] = 71,
  [72] = 68,
  [73] = 73,
  [74] = 74,
  [75] = 74,
  [76] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\n') SKIP(16)
      if (lookahead == '\r') SKIP(13)
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '&') ADVANCE(26);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == '+') ADVANCE(24);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == ';') ADVANCE(34);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '|') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'm') ADVANCE(2);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(1);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'a' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(1);
      if (lookahead == 'x') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(7);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(1);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      if (eof) ADVANCE(17);
      if (lookahead == '\t') ADVANCE(18);
      if (lookahead == '\n') SKIP(11)
      if (lookahead == '\r') SKIP(12)
      if (lookahead == ' ') SKIP(12)
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '_') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 12:
      if (eof) ADVANCE(17);
      if (lookahead == '\t') ADVANCE(18);
      if (lookahead == '\n') SKIP(11)
      if (lookahead == '\r') SKIP(14)
      if (lookahead == ' ') SKIP(12)
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '_') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 13:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(0)
      END_STATE();
    case 14:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(12)
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\n') SKIP(16)
      if (lookahead == '\r') SKIP(13)
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '&') ADVANCE(26);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == '+') ADVANCE(24);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == ';') ADVANCE(34);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '|') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\n') SKIP(16)
      if (lookahead == '\r') SKIP(15)
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '&') ADVANCE(26);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == '+') ADVANCE(24);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == ';') ADVANCE(34);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '|') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_chunks);
      if (lookahead == '\t') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '\r') SKIP(2)
      if (lookahead == 'd') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == 'w') ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '\r') SKIP(9)
      if (lookahead == 'd') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == 'w') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(0)
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'h') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '\r') SKIP(2)
      if (lookahead == 'd') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == 'w') ADVANCE(8);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 12, .external_lex_state = 1},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 1},
  [6] = {.lex_state = 0, .external_lex_state = 1},
  [7] = {.lex_state = 0, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 1},
  [9] = {.lex_state = 0, .external_lex_state = 1},
  [10] = {.lex_state = 0, .external_lex_state = 1},
  [11] = {.lex_state = 0, .external_lex_state = 1},
  [12] = {.lex_state = 0, .external_lex_state = 1},
  [13] = {.lex_state = 0, .external_lex_state = 1},
  [14] = {.lex_state = 0, .external_lex_state = 1},
  [15] = {.lex_state = 0, .external_lex_state = 1},
  [16] = {.lex_state = 0, .external_lex_state = 1},
  [17] = {.lex_state = 0, .external_lex_state = 1},
  [18] = {.lex_state = 0, .external_lex_state = 1},
  [19] = {.lex_state = 0, .external_lex_state = 1},
  [20] = {.lex_state = 0, .external_lex_state = 1},
  [21] = {.lex_state = 0, .external_lex_state = 1},
  [22] = {.lex_state = 0, .external_lex_state = 1},
  [23] = {.lex_state = 0, .external_lex_state = 1},
  [24] = {.lex_state = 0, .external_lex_state = 1},
  [25] = {.lex_state = 0, .external_lex_state = 1},
  [26] = {.lex_state = 0, .external_lex_state = 1},
  [27] = {.lex_state = 0, .external_lex_state = 1},
  [28] = {.lex_state = 0, .external_lex_state = 1},
  [29] = {.lex_state = 0, .external_lex_state = 1},
  [30] = {.lex_state = 0, .external_lex_state = 1},
  [31] = {.lex_state = 0, .external_lex_state = 1},
  [32] = {.lex_state = 0, .external_lex_state = 1},
  [33] = {.lex_state = 0, .external_lex_state = 1},
  [34] = {.lex_state = 0, .external_lex_state = 1},
  [35] = {.lex_state = 0, .external_lex_state = 1},
  [36] = {.lex_state = 0, .external_lex_state = 1},
  [37] = {.lex_state = 0, .external_lex_state = 1},
  [38] = {.lex_state = 0, .external_lex_state = 1},
  [39] = {.lex_state = 0, .external_lex_state = 1},
  [40] = {.lex_state = 0, .external_lex_state = 1},
  [41] = {.lex_state = 0, .external_lex_state = 1},
  [42] = {.lex_state = 0, .external_lex_state = 1},
  [43] = {.lex_state = 0, .external_lex_state = 1},
  [44] = {.lex_state = 0, .external_lex_state = 1},
  [45] = {.lex_state = 0, .external_lex_state = 1},
  [46] = {.lex_state = 0, .external_lex_state = 1},
  [47] = {.lex_state = 0, .external_lex_state = 1},
  [48] = {.lex_state = 0, .external_lex_state = 1},
  [49] = {.lex_state = 0, .external_lex_state = 1},
  [50] = {.lex_state = 0, .external_lex_state = 1},
  [51] = {.lex_state = 0, .external_lex_state = 1},
  [52] = {.lex_state = 0, .external_lex_state = 1},
  [53] = {.lex_state = 0, .external_lex_state = 1},
  [54] = {.lex_state = 0, .external_lex_state = 1},
  [55] = {.lex_state = 0, .external_lex_state = 1},
  [56] = {.lex_state = 0, .external_lex_state = 1},
  [57] = {.lex_state = 0, .external_lex_state = 1},
  [58] = {.lex_state = 0, .external_lex_state = 1},
  [59] = {.lex_state = 0, .external_lex_state = 1},
  [60] = {.lex_state = 0, .external_lex_state = 1},
  [61] = {.lex_state = 0, .external_lex_state = 1},
  [62] = {.lex_state = 0, .external_lex_state = 1},
  [63] = {.lex_state = 0, .external_lex_state = 1},
  [64] = {.lex_state = 0, .external_lex_state = 1},
  [65] = {.lex_state = 0, .external_lex_state = 1},
  [66] = {.lex_state = 0, .external_lex_state = 1},
  [67] = {.lex_state = 0, .external_lex_state = 1},
  [68] = {.lex_state = 0, .external_lex_state = 1},
  [69] = {.lex_state = 0, .external_lex_state = 1},
  [70] = {.lex_state = 0, .external_lex_state = 1},
  [71] = {.lex_state = 0, .external_lex_state = 1},
  [72] = {.lex_state = 0, .external_lex_state = 1},
  [73] = {.lex_state = 0, .external_lex_state = 1},
  [74] = {.lex_state = 0, .external_lex_state = 1},
  [75] = {.lex_state = 0, .external_lex_state = 1},
  [76] = {.lex_state = 0, .external_lex_state = 1},
};

enum {
  ts_external_token_comment = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(76),
    [sym__expr] = STATE(66),
    [sym_func_call] = STATE(66),
    [sym_binop] = STATE(66),
    [sym_unop] = STATE(66),
    [sym__parenthesis_exp] = STATE(66),
    [sym_if_expr] = STATE(66),
    [sym_while_expr] = STATE(66),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_chunks] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_while] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [sym_nil] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [26] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(25), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [60] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [86] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [112] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(45), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [146] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_else,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(47), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_do,
  [182] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [208] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 12,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [238] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(55), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [270] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 14,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [298] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [324] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [350] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [376] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(67), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
  [410] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_RPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(83), 1,
      sym_nil,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(27), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [448] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(89), 1,
      sym_nil,
    ACTIONS(87), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(34), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [486] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    ACTIONS(95), 1,
      sym_nil,
    ACTIONS(93), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(29), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [524] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    ACTIONS(101), 1,
      sym_nil,
    ACTIONS(99), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [562] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_while,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DASH,
    ACTIONS(109), 1,
      sym_nil,
    ACTIONS(107), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(57), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [597] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(113), 1,
      sym_nil,
    ACTIONS(111), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(65), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [632] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(117), 1,
      sym_nil,
    ACTIONS(115), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(64), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [667] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_while,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DASH,
    ACTIONS(121), 1,
      sym_nil,
    ACTIONS(119), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(58), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [702] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_while,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      sym_nil,
    ACTIONS(123), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(54), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [737] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(129), 1,
      sym_nil,
    ACTIONS(127), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(63), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [772] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_func_call_repeat1,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [807] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_func_call_repeat1,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [842] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_while,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DASH,
    ACTIONS(139), 1,
      sym_nil,
    ACTIONS(137), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(47), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [877] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    STATE(68), 1,
      aux_sym__parenthesis_exp_repeat1,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [912] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(147), 1,
      sym_nil,
    ACTIONS(145), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(15), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [947] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(151), 1,
      sym_nil,
    ACTIONS(149), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(62), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [982] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(155), 1,
      sym_nil,
    ACTIONS(153), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(59), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1017] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(159), 1,
      sym_nil,
    ACTIONS(157), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(3), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1052] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__parenthesis_exp_repeat1,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1087] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_while,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DASH,
    ACTIONS(165), 1,
      sym_nil,
    ACTIONS(163), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(52), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1122] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(169), 1,
      sym_nil,
    ACTIONS(167), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(51), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1157] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_while,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DASH,
    ACTIONS(173), 1,
      sym_nil,
    ACTIONS(171), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(55), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1192] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(177), 1,
      sym_nil,
    ACTIONS(175), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1227] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_while,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DASH,
    ACTIONS(181), 1,
      sym_nil,
    ACTIONS(179), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(48), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1262] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(185), 1,
      sym_nil,
    ACTIONS(183), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(7), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1297] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_while,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DASH,
    ACTIONS(189), 1,
      sym_nil,
    ACTIONS(187), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(46), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1332] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(193), 1,
      sym_nil,
    ACTIONS(191), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(9), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1367] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(197), 1,
      sym_nil,
    ACTIONS(195), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(10), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1402] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(201), 1,
      sym_nil,
    ACTIONS(199), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(11), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1437] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_while,
    ACTIONS(205), 1,
      sym_nil,
    ACTIONS(203), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(12), 7,
      sym__expr,
      sym_func_call,
      sym_binop,
      sym_unop,
      sym__parenthesis_exp,
      sym_if_expr,
      sym_while_expr,
  [1472] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(209), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(211), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 4,
      ts_builtin_sym_end,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_else,
    ACTIONS(213), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1500] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      anon_sym_else,
    ACTIONS(207), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(209), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(211), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(213), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1530] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_else,
    ACTIONS(207), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(209), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(211), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(213), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1560] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 12,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_else,
  [1582] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 12,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_else,
  [1604] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(217), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1634] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 12,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_else,
  [1656] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 12,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_else,
  [1678] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      anon_sym_else,
    ACTIONS(207), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(209), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(211), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(213), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1708] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(207), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(55), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_else,
  [1732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 12,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_else,
  [1754] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(207), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(209), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(55), 8,
      ts_builtin_sym_end,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_else,
  [1780] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(219), 1,
      anon_sym_else,
    ACTIONS(207), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(209), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(211), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(213), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1812] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(221), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1842] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 12,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_else,
  [1864] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 12,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_else,
  [1886] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_then,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1915] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_then,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1944] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_do,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1973] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_do,
    ACTIONS(27), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2002] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
    ACTIONS(207), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(209), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(211), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(213), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2031] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    ACTIONS(233), 1,
      anon_sym_SEMI,
    STATE(67), 1,
      aux_sym__parenthesis_exp_repeat1,
  [2044] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym__parenthesis_exp_repeat1,
  [2057] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_func_call_repeat1,
  [2070] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_func_call_repeat1,
  [2083] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_func_call_repeat1,
  [2096] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym__parenthesis_exp_repeat1,
  [2109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
  [2116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LPAREN,
  [2123] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_LPAREN,
  [2130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 86,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 146,
  [SMALL_STATE(8)] = 182,
  [SMALL_STATE(9)] = 208,
  [SMALL_STATE(10)] = 238,
  [SMALL_STATE(11)] = 270,
  [SMALL_STATE(12)] = 298,
  [SMALL_STATE(13)] = 324,
  [SMALL_STATE(14)] = 350,
  [SMALL_STATE(15)] = 376,
  [SMALL_STATE(16)] = 410,
  [SMALL_STATE(17)] = 448,
  [SMALL_STATE(18)] = 486,
  [SMALL_STATE(19)] = 524,
  [SMALL_STATE(20)] = 562,
  [SMALL_STATE(21)] = 597,
  [SMALL_STATE(22)] = 632,
  [SMALL_STATE(23)] = 667,
  [SMALL_STATE(24)] = 702,
  [SMALL_STATE(25)] = 737,
  [SMALL_STATE(26)] = 772,
  [SMALL_STATE(27)] = 807,
  [SMALL_STATE(28)] = 842,
  [SMALL_STATE(29)] = 877,
  [SMALL_STATE(30)] = 912,
  [SMALL_STATE(31)] = 947,
  [SMALL_STATE(32)] = 982,
  [SMALL_STATE(33)] = 1017,
  [SMALL_STATE(34)] = 1052,
  [SMALL_STATE(35)] = 1087,
  [SMALL_STATE(36)] = 1122,
  [SMALL_STATE(37)] = 1157,
  [SMALL_STATE(38)] = 1192,
  [SMALL_STATE(39)] = 1227,
  [SMALL_STATE(40)] = 1262,
  [SMALL_STATE(41)] = 1297,
  [SMALL_STATE(42)] = 1332,
  [SMALL_STATE(43)] = 1367,
  [SMALL_STATE(44)] = 1402,
  [SMALL_STATE(45)] = 1437,
  [SMALL_STATE(46)] = 1472,
  [SMALL_STATE(47)] = 1500,
  [SMALL_STATE(48)] = 1530,
  [SMALL_STATE(49)] = 1560,
  [SMALL_STATE(50)] = 1582,
  [SMALL_STATE(51)] = 1604,
  [SMALL_STATE(52)] = 1634,
  [SMALL_STATE(53)] = 1656,
  [SMALL_STATE(54)] = 1678,
  [SMALL_STATE(55)] = 1708,
  [SMALL_STATE(56)] = 1732,
  [SMALL_STATE(57)] = 1754,
  [SMALL_STATE(58)] = 1780,
  [SMALL_STATE(59)] = 1812,
  [SMALL_STATE(60)] = 1842,
  [SMALL_STATE(61)] = 1864,
  [SMALL_STATE(62)] = 1886,
  [SMALL_STATE(63)] = 1915,
  [SMALL_STATE(64)] = 1944,
  [SMALL_STATE(65)] = 1973,
  [SMALL_STATE(66)] = 2002,
  [SMALL_STATE(67)] = 2031,
  [SMALL_STATE(68)] = 2044,
  [SMALL_STATE(69)] = 2057,
  [SMALL_STATE(70)] = 2070,
  [SMALL_STATE(71)] = 2083,
  [SMALL_STATE(72)] = 2096,
  [SMALL_STATE(73)] = 2109,
  [SMALL_STATE(74)] = 2116,
  [SMALL_STATE(75)] = 2123,
  [SMALL_STATE(76)] = 2130,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesis_exp, 2),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesis_exp, 2),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expr, 6, .production_id = 3),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 5, .production_id = 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_call, 5, .production_id = 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 4, .production_id = 1),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_call, 4, .production_id = 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_expr, 4, .production_id = 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expr, 4, .production_id = 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesis_exp, 4),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesis_exp, 4),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop, 3),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop, 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 3, .production_id = 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_call, 3, .production_id = 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesis_exp, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesis_exp, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unop, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parenthesis_exp_repeat1, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [233] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parenthesis_exp_repeat1, 2), SHIFT_REPEAT(32),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2), SHIFT_REPEAT(36),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [251] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_tiger_external_scanner_create(void);
void tree_sitter_tiger_external_scanner_destroy(void *);
bool tree_sitter_tiger_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_tiger_external_scanner_serialize(void *, char *);
void tree_sitter_tiger_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tiger(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_tiger_external_scanner_create,
      tree_sitter_tiger_external_scanner_destroy,
      tree_sitter_tiger_external_scanner_scan,
      tree_sitter_tiger_external_scanner_serialize,
      tree_sitter_tiger_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
